title: "MeshCluster, https://idea2030.github.io/meshcluster/"
description: "MeshCluster a novel distributed system architecture for managing local energy and computing resources, MESH CLUSTER: Adaptive Infrastructure for Critical Situations"
mermaid:
  src: "mermaid.js"
plugins:
  - "jekyll-github-metadata"
  - "jekyll-readme-index"
readme_index:
  enabled:          true
  remove_originals: false
  with_frontmatter: false
